### ISSUE TITLE
Performance regression after updating to 2.5.0

### ISSUE THREAD

**Issue by sdil** [Tochemey/goakt#412]
**Bug description**

I'm building a [demo web app](https://github.com/sdil/goakt-realtimemap) using goakt. It spawns over 600 vehicle actors during its runtime.

With goakt version 2.4.0, I can get over 35k rps when running load test for the request to get the vehicle position. The memory usage is over 17GB.

```
> hey -c 100 "http://localhost:8080/vehicle?id=0012.02247" -z 30s
Summary:
  Success rate:	1.0000
  Total:	30.0036 secs
  Slowest:	0.4775 secs
  Fastest:	0.0000 secs
  Average:	0.0028 secs
  Requests/sec:	35629.9656
```

After updating to version 2.5.0, the number of rps dropped to only 3.5k. The memory usage is only <40MB (which is superb).

```
> hey -c 50 "http://localhost:8080/vehicle?id=0018.00222" -z 30s
Summary:
  Success rate:	1.0000
  Total:	30.0029 secs
  Slowest:	0.3449 secs
  Fastest:	0.0001 secs
  Average:	0.0139 secs
  Requests/sec:	3588.8494
```

**How to reproduce it?**

1. Clone my repo https://github.com/sdil/goakt-realtimemap
2. Run the server with `go run .` on first terminal
3. Run load test on `/vehicle?id=<actor name>` endpoint. I'm using https://github.com/rakyll/hey so the full command looks like this: `hey -c 50 "http://localhost:8080/vehicle?id=<actor name>" -z 30s`. You can get the actor name from the log in the terminal
4. Observe the throughput.

Change the goakt version to 2.4.0 and repeat the same process.

**Expected behavior**

The performance to remain around the same.

**Screenshots**

N/A

**Library Version:**
 - Go-Akt version: 2.5.0
 - Go version: go1.22.5 darwin/arm64

**Additional context**

When running with 1 actor, the performance is kinda similar. But when I spawn 10 actors, it started degrading significantly.

**Comment by Tochemey** [comment]
@sdil Thanks for the bug. I will take a look in the course of the week.

**Comment by Tochemey** [comment]
@sdil Do I need additional tools before running your sample?

**Comment by sdil** [comment]
@Tochemey I've updated the step on how reproduce the bug

**Comment by Tochemey** [comment]
> @Tochemey I've updated the step on how reproduce the bug

When I run `go run .` as stated I got the following log. Is it something that is expected?
<img width="1260" alt="image" src="https://github.com/user-attachments/assets/1336df38-99b3-4f9c-8e05-4f4b3762f362">

**Comment by sdil** [comment]
Yes that is expected. The program listen mqtt messages, creates actor and update its state based on the messages

**Comment by Tochemey** [comment]
@sdil I have been able to reproduce it. I will take a look at what may be the issue in the weekend. Thanks

**Comment by Tochemey** [comment]
@sdil I have added some small test to check actors message handling throughput as shown here:
```
=== RUN   TestBenchmark_Bench
starting benchmark for (20s): num workers:(50)
workers: 50, messages sent: 61522113, messages received: 61522113 - duration: 20s
messages per second: 3076105
--- PASS: TestBenchmark_Bench (42.65s)
PASS
```
The test can be found here https://github.com/Tochemey/goakt/blob/issue-perf/bench/benchmark_test.go#L165

**Comment by Tochemey** [comment]
I will enhance this benchmark test with additional test cases.

**Comment by sdil** [comment]
Ahh the Tell operation is fantastic. I didn't realize that Ask is 1/10 of the throughput of Tell. That's a really great benchmark test.

Just curious, what is your machine spec?

**Comment by Tochemey** [comment]
> Ahh the Tell operation is fantastic. I didn't realize that Ask is 1/10 of the throughput of Tell. That's a really great benchmark test.
> 
> Just curious, what is your machine spec?

13-inch M1 2020, 16GB mem, macOS

**Comment by Tochemey** [comment]
@sdil Apologies for the delay in figuring out what may be causing the performance drop. I welcome any idea to enhance performance and the library in general.

**Comment by sdil** [comment]
Did you consider [MPSC queue as suggested](https://github.com/Tochemey/goakt/pull/404#discussion_r1706849792) by @halturin? It seems like the same queue implemented in Akka

Ref: https://concurrencyfreaks.blogspot.com/2014/04/multi-producer-single-consumer-queue.html

**Comment by Tochemey** [comment]
> Did you consider [MPSC queue as suggested](https://github.com/Tochemey/goakt/pull/404#discussion_r1706849792) by @halturin? It seems like the same queue implemented in Akka
> 
> Ref: https://concurrencyfreaks.blogspot.com/2014/04/multi-producer-single-consumer-queue.html

Thanks. I am going to give it a try :)

**Comment by Tochemey** [comment]
@sdil using the mpsc queue seems increase some throughput:
```
=== RUN   TestBenchmark_BenchTell
starting benchmark for (30s): num workers:(50)
total actors spawned: (2000)
total workers: (50), total messages sent: (105993035), total messages received: (105993035) - duration: (30s)
messages per second: (3533101)
--- PASS: TestBenchmark_BenchTell (52.73s)
PASS
```

**Comment by halturin** [comment]
@Tochemey in ergo, mpsc gives me 6M msg/sec between two local actors https://github.com/ergo-services/benchmarks

**Comment by Tochemey** [comment]
> @Tochemey in ergo, mpsc gives me 6M msg/sec between two local actors https://github.com/ergo-services/benchmarks (this perf depends on the HW for sure)

my benchmarks are only for sending messages to an actor not even actor to actor :). Pretty sure something is wrong in my implementation.

**Comment by halturin** [comment]
@Tochemey i believe you can reach the same numbers easily

**Comment by Tochemey** [comment]
> @Tochemey i believe you can reach the same numbers easily

I hope so :)

**Comment by Tochemey** [comment]
Also let me take a look at ergo, maybe I may abandon Go-Akt and redirect people to ergo as long as it does not require licensing :) because that is the goal of Go-Akt

**Comment by halturin** [comment]
see v300 then :) its about to release. preparing the docs now. planned for coming September. 

https://github.com/ergo-services/examples/tree/v300 - examples. see "demo" there (it has "observer" app embedded, open http://localhost:9911 to see the node/network/processes etc)

**Comment by Tochemey** [comment]
@halturin I appreciate the support to help my library to be better. I really do. I will be glad to contribute to ergo. I have few questions to ask:

- Does ergo support actor redeployment in case network partition or cluster topology changes?
- How does clustering work?
- What are the current cluster provider engine integration?(k8, NATS, etc...)

**Comment by halturin** [comment]
> What are the current cluster provider engine integration?(k8, NATS, etc...)

its in the roadmap now. 

didnt get the first two.

> maybe I may abandon Go-Akt and redirect people to ergo as long as it does not require licensing :) because that is the goal of Go-Akt.

please, don't. we might have different vision of "where to go/how to do".

**Comment by sdil** [comment]
Personally, I liked go-akt syntaxes because it feels closer to MS Orleans. I really liked that I can do scheduling, passivation, etc. I was abit struggled with proto messaging, but that's because I never used it. Now I understand the type checking it provides. 

Ergo looks nice too but I haven't give it a try yet. Ergo looks closer to Erlang & OTP but I struggled with Elixir in the past because of its syntax and paradigm.

**Comment by Tochemey** [comment]
@sdil I am trying to see if I can the performance match ergo :)

**Comment by Tochemey** [comment]
@sdil I have released [2.5.1](https://github.com/Tochemey/goakt/releases/tag/v2.5.1) to include the mspc queue and few fixes. At the moment, Go-Akt is not yet close to ergo. Let us leave the issue open while I dig more in some the implementation and see where we can gain some more performance.

**Comment by halturin** [comment]
I noticed you used generics for your mpsc implementation. I believe, I tried this way and moved back to the 'any" type due to performance issues. But, honestly I had no enough time to dig into it.

**Comment by sdil** [comment]
Thank you for the release @Tochemey great work! I'm pretty sure we can find some other optimizations in the future 😀

**Comment by Tochemey** [comment]
Please let us leave the issue open.

**Comment by Tochemey** [comment]
> I noticed you used generics for your mpsc implementation. I believe, I tried this way and moved back to the 'any" type due to performance issues. But, honestly I had no enough time to dig into it.

Interesting. Let me take your advice and see the outcome. Thanks for pointing out.

**Comment by Tochemey** [comment]
@halturin I will be glad to have a chat with you to help fix some of the bottleneck that is hindering performance.

**Comment by sdil** [comment]
@Tochemey i was following a series of your development in these PRs

- https://github.com/Tochemey/goakt/pull/429
- https://github.com/Tochemey/goakt/pull/427
- https://github.com/Tochemey/goakt/pull/430

I remember i saw a huge performance gain from these PRs. just curious, why are they not merged?

**Comment by Tochemey** [comment]
@sdil I closed those PRs because some of the changes have been added into other PRs which has been merged. However, I have not fully tested the new changes I made. :)

**Comment by Tochemey** [comment]
@sdil you can reference the latest main commit and see

**Comment by Tochemey** [comment]
@sdil I have released a new version https://github.com/Tochemey/goakt/releases/tag/v2.6.0

**Comment by sdil** [comment]
Ahh i saw that this morning. I'll give it a try later

**Comment by sdil** [comment]
@Tochemey I'm still seeing bad load test result here

```
fyaacob@M1622 ~> hey -c 50 "http://localhost:8080/vehicle?id=0022.00945" -z 30s
Summary:
  Success rate:	1.0000
  Total:	30.0016 secs
  Slowest:	1.7371 secs
  Fastest:	0.0005 secs
  Average:	0.4966 secs
  Requests/sec:	100.0948

  Total data:	1.62 MiB
  Size/request:	566 B
  Size/sec:	55.34 KiB
```

Plus the CPU is taking 900% now.

![image](https://github.com/user-attachments/assets/27ed5607-fb93-4eb3-9fb0-0108feb17472)

This is commit for updating the library https://github.com/sdil/goakt-realtimemap/commit/84143d7fd8168497a1753467306362573d6c5a29

Let me know if messed up with anything 🙏

**Comment by Tochemey** [comment]
@sdil I will have through your implementation and see what is going on.

**Comment by Tochemey** [comment]
> @sdil I will have through your implementation and see what is going on.

This bench code [here](https://github.com/Tochemey/goakt/blob/main/bench/benchmark_test.go#L154) on my machine returns this output:

```bash
=== RUN   TestBenchmark_BenchAsk
Starting benchmark for (30s): num workers:(100)
Total workers: (100), total messages sent: (29025818), total messages received: (29025818) - duration: (30s)
Messages per second: (967527)
--- PASS: TestBenchmark_BenchAsk (32.53s)
PASS
```

It spawns 100 workers to send Ask to a given actor.

**Comment by Tochemey** [comment]
and this bench code [here](https://github.com/Tochemey/goakt/blob/main/bench/benchmark_test.go#L83) on my machine returns this output:

```bash
goos: darwin
goarch: arm64
pkg: github.com/tochemey/goakt/v2/bench
cpu: Apple M1
BenchmarkActor
BenchmarkActor/ask
BenchmarkActor/ask-8         	 1099460	       984.2 ns/op	   1035262 ops/s	     577 B/op	      10 allocs/op
PASS

```

**Comment by Tochemey** [comment]
@sdil I hope these give you some idea. I will look into your implementation when I get some spare time.

**Comment by Tochemey** [comment]
@sdil at first glance I can see some loop [here](https://github.com/sdil/goakt-realtimemap/blob/main/main.go#L101) constantly querying for actors. I don't know what you want to achieve though but this can be an issue.

**Comment by sdil** [comment]
I'm running the bench test on my machine and getting this

```
> make bench
cd bench && rm -f bench.txt && go test -run=^# -bench . -benchmem -count=30 -timeout=0 | tee bench.txt
goos: darwin
goarch: arm64
pkg: github.com/tochemey/goakt/v2/bench
cpu: Apple M1 Pro
BenchmarkActor/tell-10              3304     608753 ns/op    3865833 ops/s      312 B/op        6 allocs/op
BenchmarkActor/tell-10              3435     585545 ns/op    3740811 ops/s      301 B/op        6 allocs/op
BenchmarkActor/tell-10              3436     585312 ns/op    4126291 ops/s      308 B/op        6 allocs/op
BenchmarkActor/tell-10              3439     584775 ns/op    4174597 ops/s      301 B/op        6 allocs/op
```

I think something is wrong with my machine. I restarted my machine and it's still showing the same result

**Comment by Tochemey** [comment]
@sdil I will be glad to sync with you if you are free. :). I can send you an invite on linkedin

**Comment by sdil** [comment]
@Tochemey yup I'm free right now. this is my linkedin https://www.linkedin.com/in/fadhilyaacob/

**Comment by Tochemey** [comment]
> @Tochemey yup I'm free right now. this is my linkedin https://www.linkedin.com/in/fadhilyaacob/

@sdil send me a message because it seems I need to activate premium feature before sending you a message. This is mine https://github.com/sdil/goakt-realtimemap/blob/main/main.go#L101

**Comment by sdil** [comment]
that's not a linkedin URL 😛

**Comment by sdil** [comment]
I can't message you either.

**Comment by Tochemey** [comment]
> that's not a linkedin URL 😛
> 
> Found it from your github profile

Hahaa. sorry bro: https://meet.google.com/xsf-dcyf-fjn?authuser=0&pli=1

**Comment by Tochemey** [comment]
@sdil these are the benchmark results on my machine:

```bash
cd bench && rm -f bench.txt && go test -run=^# -bench . -benchmem -cpu=16 -count=10 | tee bench.txt
goos: darwin
goarch: arm64
pkg: github.com/tochemey/goakt/v2/bench
cpu: Apple M1
BenchmarkActor/tell-16         	    3314	    606899 ns/op	   3419724 ops/s	     308 B/op	       6 allocs/op
BenchmarkActor/tell-16         	    3421	    587953 ns/op	   3464890 ops/s	     303 B/op	       6 allocs/op
BenchmarkActor/tell-16         	    3458	    581630 ns/op	   3568473 ops/s	     302 B/op	       6 allocs/op
BenchmarkActor/tell-16         	    3454	    582282 ns/op	   3370989 ops/s	     302 B/op	       6 allocs/op
BenchmarkActor/tell-16         	    3444	    583975 ns/op	   3359315 ops/s	     312 B/op	       6 allocs/op
BenchmarkActor/tell-16         	    3450	    582916 ns/op	   3659670 ops/s	     301 B/op	       6 allocs/op
BenchmarkActor/tell-16         	    3457	    581736 ns/op	   3532655 ops/s	     302 B/op	       6 allocs/op
BenchmarkActor/tell-16         	    3446	    583620 ns/op	   3503963 ops/s	     302 B/op	       6 allocs/op
BenchmarkActor/tell-16         	    3444	    583934 ns/op	   3551735 ops/s	     302 B/op	       6 allocs/op
BenchmarkActor/tell-16         	    3459	    581408 ns/op	   3568124 ops/s	     302 B/op	       6 allocs/op
BenchmarkActor/ask-16          	 1130342	       966.6 ns/op	   1053943 ops/s	     582 B/op	      10 allocs/op
BenchmarkActor/ask-16          	 1161424	       967.1 ns/op	   1052861 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-16          	 1164417	       967.5 ns/op	   1052337 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-16          	 1125428	       967.2 ns/op	   1053302 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-16          	 1146259	       976.0 ns/op	   1043344 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-16          	 1162370	       969.2 ns/op	   1050534 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-16          	 1158091	       975.4 ns/op	   1043822 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-16          	 1154194	       981.9 ns/op	   1036775 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-16          	 1166288	       968.6 ns/op	   1051095 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-16          	 1154174	       981.5 ns/op	   1037217 ops/s	     576 B/op	      10 allocs/op
PASS
ok  	github.com/tochemey/goakt/v2/bench	194.740s
```

```bash
cd bench && rm -f bench.txt && go test -run=^# -bench . -benchmem -cpu=64 -count=10 | tee bench.txt
goos: darwin
goarch: arm64
pkg: github.com/tochemey/goakt/v2/bench
cpu: Apple M1
BenchmarkActor/tell-64         	    3298	    609897 ns/op	   2955308 ops/s	     354 B/op	       6 allocs/op
BenchmarkActor/tell-64         	    3402	    591229 ns/op	   2697057 ops/s	     329 B/op	       6 allocs/op
BenchmarkActor/tell-64         	    3412	    589500 ns/op	   2814118 ops/s	     320 B/op	       6 allocs/op
BenchmarkActor/tell-64         	    3404	    590840 ns/op	   3612948 ops/s	     310 B/op	       6 allocs/op
BenchmarkActor/tell-64         	  191126	     10791 ns/op	   3664785 ops/s	     296 B/op	       6 allocs/op
BenchmarkActor/tell-64         	    3415	    589012 ns/op	   3017118 ops/s	     323 B/op	       6 allocs/op
BenchmarkActor/tell-64         	    3357	    599198 ns/op	   2940115 ops/s	     310 B/op	       6 allocs/op
BenchmarkActor/tell-64         	    3432	    586095 ns/op	   2924168 ops/s	     322 B/op	       6 allocs/op
BenchmarkActor/tell-64         	  190279	     10906 ns/op	   2930726 ops/s	     296 B/op	       6 allocs/op
BenchmarkActor/tell-64         	    3414	    589249 ns/op	   3017012 ops/s	     336 B/op	       6 allocs/op
BenchmarkActor/ask-64          	 1076030	      1024 ns/op	    994416 ops/s	     581 B/op	      10 allocs/op
BenchmarkActor/ask-64          	 1098844	      1011 ns/op	   1007668 ops/s	     577 B/op	      10 allocs/op
BenchmarkActor/ask-64          	 1179016	      1008 ns/op	   1008829 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-64          	 1108654	      1015 ns/op	   1002926 ops/s	     577 B/op	      10 allocs/op
BenchmarkActor/ask-64          	 1114039	      1027 ns/op	    991018 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-64          	 1109829	      1003 ns/op	   1015062 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-64          	 1105442	      1011 ns/op	   1007678 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-64          	 1130664	      1011 ns/op	   1006370 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-64          	 1105929	      1016 ns/op	   1002137 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-64          	 1103197	      1012 ns/op	   1006636 ops/s	     576 B/op	      10 allocs/op
PASS
ok  	github.com/tochemey/goakt/v2/bench	199.049s
```

```bash
cd bench && rm -f bench.txt && go test -run=^# -bench . -benchmem -cpu=10 -count=10 | tee bench.txt                                                                    took  3m 20s at  06:18:32 pm
goos: darwin
goarch: arm64
pkg: github.com/tochemey/goakt/v2/bench
cpu: Apple M1
BenchmarkActor/tell-10         	  185508	     11084 ns/op	   4026571 ops/s	     296 B/op	       6 allocs/op
BenchmarkActor/tell-10         	    3444	    583985 ns/op	   3550365 ops/s	     301 B/op	       6 allocs/op
BenchmarkActor/tell-10         	    3445	    583769 ns/op	   3601989 ops/s	     301 B/op	       6 allocs/op
BenchmarkActor/tell-10         	    3454	    582288 ns/op	   3627675 ops/s	     301 B/op	       6 allocs/op
BenchmarkActor/tell-10         	    3450	    582920 ns/op	   3549536 ops/s	     302 B/op	       6 allocs/op
BenchmarkActor/tell-10         	    3462	    580915 ns/op	   3526956 ops/s	     301 B/op	       6 allocs/op
BenchmarkActor/tell-10         	    3448	    583290 ns/op	   3574290 ops/s	     306 B/op	       6 allocs/op
BenchmarkActor/tell-10         	    3458	    581576 ns/op	   3521833 ops/s	     300 B/op	       6 allocs/op
BenchmarkActor/tell-10         	    3447	    583429 ns/op	   3584557 ops/s	     301 B/op	       6 allocs/op
BenchmarkActor/tell-10         	    3456	    581910 ns/op	   3632954 ops/s	     301 B/op	       6 allocs/op
BenchmarkActor/ask-10          	 1162461	       957.4 ns/op	   1063679 ops/s	     578 B/op	      10 allocs/op
BenchmarkActor/ask-10          	 1178132	       968.8 ns/op	   1050724 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-10          	 1186813	       969.9 ns/op	   1049383 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-10          	 1166163	       962.7 ns/op	   1057649 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-10          	 1164457	       956.7 ns/op	   1064486 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-10          	 1151874	       969.3 ns/op	   1050524 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-10          	 1138566	       963.5 ns/op	   1057205 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-10          	 1174144	       959.1 ns/op	   1061610 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-10          	 1148130	       962.3 ns/op	   1058367 ops/s	     576 B/op	      10 allocs/op
BenchmarkActor/ask-10          	 1183231	       967.6 ns/op	   1051966 ops/s	     576 B/op	      10 allocs/op
PASS
ok  	github.com/tochemey/goakt/v2/bench	196.840s
```

**Comment by Tochemey** [comment]
@sdil I made some small change to avoid busy thread and without any modification in your code, I am able to reach this throughput which seems promising:
<img width="1304" alt="image" src="https://github.com/user-attachments/assets/ccbe7b66-14a7-4688-ac63-c6cf8e98f92f">

**Comment by sdil** [comment]
That's pretty good. I wonder how does that change improves the performance

**Comment by Tochemey** [comment]
> That's pretty good. I wonder how does that change improves the performance

The previous implementation of the receive is just looping even when there is no messages in the mailbox which creates unnecessary busy threads. The enhancement is to react only messages are dropped in the mailbox.

**Comment by Tochemey** [comment]
@sdil closing the issue. Let us revisit it when things get worst.

**Comment by sdil** [comment]
@Tochemey sure. Thanks for your work 🙇
